const ERROR_CODES = {
  
  // EMAIL
  EMAIL_OR_PASSWORD_WRONG : "EMAIL OR PASSWORD WRONG",
  INVALID_EMAIL : "INVALID EMAIL",
  EMAIL_ALREADY_REGISTERED: "THIS EMAIL ALREADY REGISTERED",

  // PASSWORD
  WEAK_PASSWORD: "WEAK PASSWORD",
  PASSWORD_MIN : "PASSWORD MUST BE MIN 8 CHARACTERS",

  // TOKEN
  TOKEN_EXPIRED : "TOKEN EXPIRED",

  // STATUS
  SUCCESS : "SUCCESS",
  USER_NOT_FOUND : "USER NOT FOUND",
  SOMETHING_WENT_WRONG : "SOMETHING WENT WRONG",

  // PRODUCT
  PRODUCT_NAME_ERROR : "PRODUCT NAME MUST BE MIN 3 MAX 32",
  PRODUCT_DESCRIPTION_ERROR : "PRODUCT DESCRIPTION MUST BE MIN 3 MAX 32",
  PRODUCT_PRICE_LENGTH_ERROR : "PRICE MUST BE BETWEEN 1 AND 4 LENGTH",
  PRODUCT_PRICE_NUMERIC_ERROR : "PRICE JUST ONLY MUST NUMERIC",

  //MONGODB
  INVALID_MONGO_ID : "INVLALID ID"

};
export default ERROR_CODES